/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={36.18}
        position={[0.81, 4.76, 10.68]}
        rotation={[0, 0.06, 0]}
        scale={4.07}
      />
      <mesh
        geometry={nodes.background.geometry}
        material={materials.box}
        position={[-0.27, 0.38, -0.74]}
      />
      <mesh
        geometry={nodes.suzane.geometry}
        material={materials["Material.001"]}
        position={[0, 4.65, 0]}
        scale={1.51}
      />
      <mesh
        geometry={nodes.stage.geometry}
        material={materials.box}
        position={[0, 0.18, 0]}
        scale={[2.36, 0.58, 2.36]}
      />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
